repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.1
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
          - --args=--recursive
  - repo: local
    hooks:
      - id: terraform_docs
        name: terraform_docs
        entry: bash -c 'make tfdocs && git add "./README.md"'
        language: system
        types: [terraform]
        pass_filenames: false
